# render.yaml
services:
  - type: web
    name: success-box-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn chatbot_api:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
